# remap prefix from 'C-b' to 'C-b'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config
unbind r
bind r source-file ~/.tmux.conf

# vim mode
setw -g mode-keys vi

# prompt window name when creating a new one
bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

# project picker
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
# open lazygit in a popup window
bind-key g popup -E -w 90% -h 90%  -d '#{pane_current_path}' lazygit

# color support
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

# enable mouse scrolling - shift click to highlight text
set -g mouse on


# theme
## COLORSCHEME: everforest dark medium
set -g status-left ' #[fg=#B279A7,bold]#{s/root//:client_key_table} '
set -g status-right '#[fg=#B279A7,bold] [#S]#[fg=#B279A7,bold] [%d/%m] #[fg=#B279A7,bold][%I:%M%p] '
set -g status-style fg='#B279A7',bg='#F0E4CF'

set -g window-status-current-style fg='#B279A7',bg='#F0E4CF',bold

set -g pane-border-style fg='#B279A7'
set -g pane-active-border-style fg='#B279A7'

set -g message-style fg='#404040',bg='#746956'

set -g display-panes-active-colour '#B279A7'
set -g display-panes-colour '#B279A7'

set -g clock-mode-colour '#B279A7'

set -g mode-style fg='#404040',bg='#746956'

