# 
theme[main_bg]="#404040"
theme[main_fg]="#F0E4CF"

theme[title]="#F0E4CF"

theme[hi_fg]="#B77E64"

theme[selected_bg]="#625A5B"
theme[selected_fg]="#F3EADB"

theme[inactive_fg]="#625A5B"

theme[graph_text]="#C0AB86"

theme[proc_misc]="#65B8C1"

theme[cpu_box]="#625A5B"
theme[mem_box]="#625A5B"
theme[net_box]="#625A5B"
theme[proc_box]="#625A5B"

theme[div_line]="#625A5B"

theme[temp_start]="#819B69"
theme[temp_mid]="#B77E64"
theme[temp_end]="#E3716E"

theme[cpu_start]="#6099C0"
theme[cpu_mid]="#B279A7"
theme[cpu_end]="#E3716E"

theme[free_start]="#819B69"
theme[free_mid]=""
theme[free_end]=""

theme[cached_start]="#66A5AD"
theme[cached_mid]=""
theme[cached_end]=""

theme[available_start]="#B77E64"
theme[available_mid]=""
theme[available_end]=""

theme[used_start]="#6099C0"
theme[used_mid]=""
theme[used_end]=""

theme[download_start]="#6099C0"
theme[download_mid]=""
theme[download_end]="#66A5AD"

theme[upload_start]="#819B69"
theme[upload_mid]=""
theme[upload_end]="#B77E64"

theme[process_start]="#6099C0"
theme[process_mid]="#B279A7"
theme[process_end]="#E3716E"
